language: node_js
notifications:
  email: false
node_js:
  - 10
  - 8
script:
  - yarn lint:commit-travis
  - yarn lint
  - yarn build
  - yarn test
after_success: yarn coveralls
jobs:
  include:
    - stage: Release Docs
      if: branch = master
      node_js: 10
      script:
        - yarn build:docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        keep-history: true
    - stage: Release NPM
      if: branch = master
      node_js: 10
      script:
        - yarn build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
